name: deepfuse_local01   # needs more than 12 GB of RAM just for Fluo-N2DH-GOWT1...
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - tifffile
  - scipy
  - scikit-image
  - pip
  - pip:
    - tensorflow==2.10.0