name: deepfuse_local01   # intended for local test, but needs more than 12 GB of RAM just for Fluo-N2DH-GOWT1... it wasn't used at all
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - tifffile
  - scipy
  - scikit-image
  - pandas
  - pyarrow
  - dvc
  - pip
  - pip:
    - tensorflow==2.11.0
    - matplotlib
    - dvc[ssh]
